# Generated by Django 4.2.7 on 2023-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateField()),
                ('lte_existing', models.BooleanField()),
                ('slug', models.SlugField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
            ],
        ),
    ]
